### ISSUE TITLE
Calling `sha256 "digest"

### ISSUE THREAD

**Issue by wly99** [EOSIO/homebrew-eosio#54] opened 2021-06-07 15:19 UTC
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.

Hello! I faced this issue while trying to install EOS. Original warning was:
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the eosio/eosio tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/eosio/homebrew-eosio/eosio.rb:19

Read the other issue and ran "brew style --fix eosio" but still ended up with that warning at the top.

**Comment by kj4ezj** [comment] 2021-06-11 15:17
Thank you so much for reporting this, we really appreciate it!  
  
I am going to close this as a duplicate of [issue 50](https://github.com/EOSIO/homebrew-eosio/issues/50) and copy your comment to that thread. Please feel free to continue discussion on that issue as-necessary.  
  
(Internal tracking: [EPE-944](https://blockone.atlassian.net/browse/EPE-944))

**Closed by kj4ezj** 2021-06-11 15:17 UTC
